version: '3'
services:
  web:
    build: .
    command: bash start.sh
    container_name: web-jishobr
    volumes:
      - .:/var/www/jishobr
    ports:
      - 3000:3000
    links:
      - db
    env_file:
      - .env.docker
  db:
    image: postgres:10.3-alpine
    hostname: db-jishobr
    container_name: db-jishobr
    ports:
      - 6532:5432
    env_file:
      .env.docker
    volumes:
      - jishobr-data:/var/lib/postgresql/data
volumes:
  jishobr-data: