
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jishobr_development

test:
  <<: *default
  database: jishobr_test

production:
  <<: *default
  database: jishobr_production
  username: jishobr
  password: <%= ENV['JISHOBR_DATABASE_PASSWORD'] %>
